import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    name: "Organic Honey",
    brand: "BeeNatural",
    shortDescription: "Pure organic honey.",
    description:
      "This is a high-quality organic honey sourced from sustainable farms.",
    image: {
      hash: "abc123",
      url: "https://nest-frontend-v6.netlify.app/assets/imgs/shop/product-1-1.jpg",
      name: "organic-honey.jpg",
    },
    price: 10.99,
    totalPrice: 10.99,
    salePrice: 8.99,
    category: {
      id: 1,
      name: "Food & Beverage",
    },
    isFavorite: true,
    rating: 4.7,
    reviews: 120,
    totalReviews: 150,
    maxAmountPerOrder: 5,
  },
  {
    id: 2,
    name: "Natural Shampoo",
    brand: "EcoHair",
    shortDescription: "Gentle, natural ingredients.",
    description:
      "A shampoo made from natural ingredients, suitable for all hair types.",
    image: {
      hash: "def456",
      url: "https://nest-frontend-v6.netlify.app/assets/imgs/shop/product-1-1.jpg",
      name: "natural-shampoo.jpg",
    },
    price: 15.49,
    totalPrice: 15.49,
    category: {
      id: 2,
      name: "Personal Care",
    },
    isFavorite: false,
    rating: 4.3,
    reviews: 75,
    totalReviews: 80,
    maxAmountPerOrder: 3,
  },
  {
    id: 3,
    name: "Herbal Tea",
    brand: "Nature's Brew",
    shortDescription: "Calming herbal blend.",
    description:
      "A soothing blend of natural herbs for a relaxing tea experience.",
    image: {
      hash: "ghi789",
      url: "https://nest-frontend-v6.netlify.app/assets/imgs/shop/product-1-1.jpg",
      name: "herbal-tea.jpg",
    },
    price: 5.99,
    totalPrice: 5.99,
    category: {
      id: 1,
      name: "Food & Beverage",
    },
    isFavorite: true,
    rating: 4.5,
    reviews: 90,
    totalReviews: 95,
    maxAmountPerOrder: 10,
  },
  {
    id: 4,
    name: "Reusable Water Bottle",
    brand: "EcoDrink",
    shortDescription: "Eco-friendly bottle.",
    description:
      "A durable, eco-friendly water bottle made from stainless steel.",
    image: {
      hash: "jkl012",
      url: "https://nest-frontend-v6.netlify.app/assets/imgs/shop/product-1-1.jpg",
      name: "reusable-water-bottle.jpg",
    },
    price: 12.99,
    totalPrice: 12.99,
    salePrice: 10.99,
    category: {
      id: 3,
      name: "Outdoor & Sports",
    },
    isFavorite: true,
    rating: 4.8,
    reviews: 150,
    totalReviews: 160,
    maxAmountPerOrder: 4,
  },
  {
    id: 5,
    name: "Vegan Protein Powder",
    brand: "PlantPower",
    shortDescription: "Plant-based protein.",
    description:
      "A high-quality protein powder made from natural plant sources.",
    image: {
      hash: "mno345",
      url: "https://nest-frontend-v6.netlify.app/assets/imgs/shop/product-1-1.jpg",
      name: "vegan-protein-powder.jpg",
    },
    price: 20.99,
    totalPrice: 20.99,
    category: {
      id: 4,
      name: "Health & Wellness",
    },
    isFavorite: false,
    rating: 4.6,
    reviews: 130,
    totalReviews: 140,
    maxAmountPerOrder: 2,
  },
  {
    id: 6,
    name: "Eco-friendly Toothbrush",
    brand: "GreenBrush",
    shortDescription: "Biodegradable brush.",
    description:
      "A toothbrush made from bamboo, eco-friendly and biodegradable.",
    image: {
      hash: "pqr678",
      url: "https://nest-frontend-v6.netlify.app/assets/imgs/shop/product-1-1.jpg",
      name: "eco-friendly-toothbrush.jpg",
    },
    price: 3.99,
    totalPrice: 3.99,
    category: {
      id: 2,
      name: "Personal Care",
    },
    isFavorite: true,
    rating: 4.2,
    reviews: 50,
    totalReviews: 55,
    maxAmountPerOrder: 6,
  },
  {
    id: 7,
    name: "Handmade Soap",
    brand: "PureSoap",
    shortDescription: "Natural and fragrant.",
    description:
      "A handmade soap bar made from natural ingredients with a pleasant fragrance.",
    image: {
      hash: "stu901",
      url: "https://nest-frontend-v6.netlify.app/assets/imgs/shop/product-1-1.jpg",
      name: "handmade-soap.jpg",
    },
    price: 6.99,
    totalPrice: 6.99,
    category: {
      id: 2,
      name: "Personal Care",
    },
    isFavorite: false,
    rating: 4.9,
    reviews: 200,
    totalReviews: 220,
    maxAmountPerOrder: 8,
  },
  {
    id: 8,
    name: "Organic Granola",
    brand: "HealthyCrunch",
    shortDescription: "Crunchy and healthy.",
    description:
      "A delicious and healthy granola mix made from organic ingredients.",
    image: {
      hash: "vwx234",
      url: "https://nest-frontend-v6.netlify.app/assets/imgs/shop/product-1-1.jpg",
      name: "organic-granola.jpg",
    },
    price: 8.99,
    totalPrice: 8.99,
    salePrice: 7.49,
    category: {
      id: 1,
      name: "Food & Beverage",
    },
    isFavorite: true,
    rating: 4.4,
    reviews: 110,
    totalReviews: 120,
    maxAmountPerOrder: 5,
  },
  {
    id: 9,
    name: "Essential Oil Diffuser",
    brand: "AromaLife",
    shortDescription: "Aromatherapy diffuser.",
    description:
      "An essential oil diffuser for creating a calming and aromatic environment.",
    image: {
      hash: "yza567",
      url: "https://nest-frontend-v6.netlify.app/assets/imgs/shop/product-1-1.jpg",
      name: "essential-oil-diffuser.jpg",
    },
    price: 25.99,
    totalPrice: 25.99,
    category: {
      id: 5,
      name: "Home & Garden",
    },
    isFavorite: false,
    rating: 4.8,
    reviews: 180,
    totalReviews: 190,
    maxAmountPerOrder: 2,
  },
  {
    id: 10,
    name: "Yoga Mat",
    brand: "FlexYoga",
    shortDescription: "Non-slip, durable.",
    description:
      "A high-quality yoga mat with a non-slip surface, perfect for all types of yoga.",
    image: {
      hash: "bcd890",
      url: "https://nest-frontend-v6.netlify.app/assets/imgs/shop/product-1-1.jpg",
      name: "yoga-mat.jpg",
    },
    price: 22.99,
    totalPrice: 22.99,
    salePrice: 19.99,
    category: {
      id: 3,
      name: "Outdoor & Sports",
    },
    isFavorite: true,
    rating: 4.7,
    reviews: 140,
    totalReviews: 150,
    maxAmountPerOrder: 3,
  },
];
