import startApplication from "@mongez/react";
import "swiper/css";
import "swiper/css/free-mode";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/thumbs";
import "yet-another-react-lightbox/styles.css";
import "./main.css";
import "./shared/apps-list";
import "./shared/config";
startApplication();
